# application.yaml

server:
  # port: 8080
  # location on classpath (e.g. src/main/resources/WEB in maven)
  static.classpath:
    location: "/WEB"
    # this is optional, defaults to "/"
    context: "/web"
    welcome: "index.html"

grpc:
  port: 50051
  channels:                
    myserver:           
      host: localhost      
      port: 50051
   
# security settings - simple basic auth
# can work with oracle.demo.SecurityResource
security:
    providers:
    - abac:
    - http-basic-auth:
        realm: "helidon"
        users:
        - login: "john"
          password: "password1"
          roles: ["user", "admin"]
        - login: "mary"
          password: "password2"
          roles: ["user"]
        - login: "ken"
          password: "password3"

# data source settings
javax:
    sql:
        DataSource:
            DemoDataSource:
                ## default h2
                dataSourceClassName: org.h2.jdbcx.JdbcDataSource
                dataSource:
                    url: jdbc:h2:mem:greeting;INIT=RUNSCRIPT FROM 'classpath:createtable.ddl' 
                    user: sa
                    password: ""
                
                ## example config for Oracle database
                #dataSourceClassName: oracle.jdbc.pool.OracleDataSource
                #dataSource:
                #    #url: jdbc:oracle:thin:@abc_high?TNS_ADMIN=/tnsdir
                #    url: jdbc:oracle:thin:@//localhost:1521/PDB1.localdomain
                #    user: demo
                #    password: OCHaCafe6666
                
                ## example config for MySQL database
                #driverClassName: com.mysql.jdbc.Driver
                #jdbcUrl: jdbc:mysql://localhost:3306/demo
                #username: oracle
                #password: mysql

# Reactive Messaging
mp.messaging:

  incoming.from-jms:
    connector: helidon-jms
    destination: ./SystemModule-0!Queue-0
    type: queue

  outgoing.to-jms:
    connector: helidon-jms
    destination: ./SystemModule-0!Queue-0
    type: queue

  connector:
    helidon-jms:
      user: weblogic
      password: OCHaCafe6834
      jndi:
        jms-factory: weblogic.jms.ConnectionFactory
        env-properties:
          java.naming:
            factory.initial: weblogic.jndi.WLInitialContextFactory
            provider.url: t3://localhost:7001