kind: Deployment
apiVersion: apps/v1
metadata:
  name: helidon-mp-demo-deployment
  labels:
    app: helidon-mp-demo
  namespace: demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: helidon-mp-demo
  template:
    metadata:
      labels:
        app: helidon-mp-demo
    spec:
      containers:
      - name: helidon-mp-demo-container
        image: ${REMOTE_REPO_PREFIX}helidon-mp-demo:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: ocirsecret
---
